// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FileData struct {
	Filename             string   `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Mode                 int32    `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileData) Reset()         { *m = FileData{} }
func (m *FileData) String() string { return proto.CompactTextString(m) }
func (*FileData) ProtoMessage()    {}
func (*FileData) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_a5f1c3a37dc34d12, []int{0}
}
func (m *FileData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileData.Unmarshal(m, b)
}
func (m *FileData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileData.Marshal(b, m, deterministic)
}
func (dst *FileData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileData.Merge(dst, src)
}
func (m *FileData) XXX_Size() int {
	return xxx_messageInfo_FileData.Size(m)
}
func (m *FileData) XXX_DiscardUnknown() {
	xxx_messageInfo_FileData.DiscardUnknown(m)
}

var xxx_messageInfo_FileData proto.InternalMessageInfo

func (m *FileData) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *FileData) GetMode() int32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *FileData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Response struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_a5f1c3a37dc34d12, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func init() {
	proto.RegisterType((*FileData)(nil), "FileData")
	proto.RegisterType((*Response)(nil), "Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FileTransferServiceClient is the client API for FileTransferService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FileTransferServiceClient interface {
	FileTransfer(ctx context.Context, opts ...grpc.CallOption) (FileTransferService_FileTransferClient, error)
}

type fileTransferServiceClient struct {
	cc *grpc.ClientConn
}

func NewFileTransferServiceClient(cc *grpc.ClientConn) FileTransferServiceClient {
	return &fileTransferServiceClient{cc}
}

func (c *fileTransferServiceClient) FileTransfer(ctx context.Context, opts ...grpc.CallOption) (FileTransferService_FileTransferClient, error) {
	stream, err := c.cc.NewStream(ctx, &_FileTransferService_serviceDesc.Streams[0], "/FileTransferService/FileTransfer", opts...)
	if err != nil {
		return nil, err
	}
	x := &fileTransferServiceFileTransferClient{stream}
	return x, nil
}

type FileTransferService_FileTransferClient interface {
	Send(*FileData) error
	Recv() (*Response, error)
	grpc.ClientStream
}

type fileTransferServiceFileTransferClient struct {
	grpc.ClientStream
}

func (x *fileTransferServiceFileTransferClient) Send(m *FileData) error {
	return x.ClientStream.SendMsg(m)
}

func (x *fileTransferServiceFileTransferClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FileTransferServiceServer is the server API for FileTransferService service.
type FileTransferServiceServer interface {
	FileTransfer(FileTransferService_FileTransferServer) error
}

func RegisterFileTransferServiceServer(s *grpc.Server, srv FileTransferServiceServer) {
	s.RegisterService(&_FileTransferService_serviceDesc, srv)
}

func _FileTransferService_FileTransfer_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FileTransferServiceServer).FileTransfer(&fileTransferServiceFileTransferServer{stream})
}

type FileTransferService_FileTransferServer interface {
	Send(*Response) error
	Recv() (*FileData, error)
	grpc.ServerStream
}

type fileTransferServiceFileTransferServer struct {
	grpc.ServerStream
}

func (x *fileTransferServiceFileTransferServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *fileTransferServiceFileTransferServer) Recv() (*FileData, error) {
	m := new(FileData)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _FileTransferService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "FileTransferService",
	HandlerType: (*FileTransferServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FileTransfer",
			Handler:       _FileTransferService_FileTransfer_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_service_a5f1c3a37dc34d12) }

var fileDescriptor_service_a5f1c3a37dc34d12 = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8e, 0xb1, 0x0a, 0xc2, 0x30,
	0x14, 0x45, 0x8d, 0xda, 0xd2, 0x3e, 0xea, 0x12, 0x41, 0x4a, 0xa7, 0x92, 0x29, 0x38, 0x14, 0xd1,
	0x2f, 0x10, 0xc4, 0xd1, 0x21, 0xfa, 0x03, 0x4f, 0xfb, 0x0a, 0x85, 0x36, 0x29, 0x49, 0xf4, 0xfb,
	0xa5, 0xd1, 0x8a, 0xdb, 0xbd, 0x77, 0x38, 0xf7, 0xc0, 0xca, 0x91, 0x7d, 0xb5, 0x0f, 0xaa, 0x06,
	0x6b, 0xbc, 0x11, 0x17, 0x48, 0xce, 0x6d, 0x47, 0x27, 0xf4, 0xc8, 0x0b, 0x48, 0x9a, 0xb6, 0x23,
	0x8d, 0x3d, 0xe5, 0xac, 0x64, 0x32, 0x55, 0xbf, 0xce, 0x39, 0x2c, 0x7b, 0x53, 0x53, 0x3e, 0x2f,
	0x99, 0x8c, 0x54, 0xc8, 0xe3, 0x56, 0xa3, 0xc7, 0x7c, 0x51, 0x32, 0x99, 0xa9, 0x90, 0x85, 0x80,
	0x44, 0x91, 0x1b, 0x8c, 0x76, 0xc4, 0x37, 0x10, 0x3b, 0x8f, 0xfe, 0xe9, 0x02, 0x2d, 0x52, 0xdf,
	0xb6, 0x3f, 0xc2, 0x7a, 0xfc, 0xbc, 0x59, 0xd4, 0xae, 0x21, 0x7b, 0xfd, 0x08, 0xf1, 0x2d, 0x64,
	0xff, 0x33, 0x4f, 0xab, 0xc9, 0xac, 0x48, 0xab, 0x09, 0x2a, 0x66, 0x92, 0xed, 0xd8, 0x3d, 0x0e,
	0xf6, 0x87, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x69, 0x4a, 0x98, 0xb0, 0xce, 0x00, 0x00, 0x00,
}
