// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FileInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size                 int64    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Mode                 uint32   `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileInfo) Reset()         { *m = FileInfo{} }
func (m *FileInfo) String() string { return proto.CompactTextString(m) }
func (*FileInfo) ProtoMessage()    {}
func (*FileInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_38b27f0a3a5b3f28, []int{0}
}
func (m *FileInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileInfo.Unmarshal(m, b)
}
func (m *FileInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileInfo.Marshal(b, m, deterministic)
}
func (dst *FileInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileInfo.Merge(dst, src)
}
func (m *FileInfo) XXX_Size() int {
	return xxx_messageInfo_FileInfo.Size(m)
}
func (m *FileInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FileInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FileInfo proto.InternalMessageInfo

func (m *FileInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FileInfo) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *FileInfo) GetMode() uint32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

type FileData struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileData) Reset()         { *m = FileData{} }
func (m *FileData) String() string { return proto.CompactTextString(m) }
func (*FileData) ProtoMessage()    {}
func (*FileData) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_38b27f0a3a5b3f28, []int{1}
}
func (m *FileData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileData.Unmarshal(m, b)
}
func (m *FileData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileData.Marshal(b, m, deterministic)
}
func (dst *FileData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileData.Merge(dst, src)
}
func (m *FileData) XXX_Size() int {
	return xxx_messageInfo_FileData.Size(m)
}
func (m *FileData) XXX_DiscardUnknown() {
	xxx_messageInfo_FileData.DiscardUnknown(m)
}

var xxx_messageInfo_FileData proto.InternalMessageInfo

func (m *FileData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Res struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Res) Reset()         { *m = Res{} }
func (m *Res) String() string { return proto.CompactTextString(m) }
func (*Res) ProtoMessage()    {}
func (*Res) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_38b27f0a3a5b3f28, []int{2}
}
func (m *Res) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Res.Unmarshal(m, b)
}
func (m *Res) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Res.Marshal(b, m, deterministic)
}
func (dst *Res) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Res.Merge(dst, src)
}
func (m *Res) XXX_Size() int {
	return xxx_messageInfo_Res.Size(m)
}
func (m *Res) XXX_DiscardUnknown() {
	xxx_messageInfo_Res.DiscardUnknown(m)
}

var xxx_messageInfo_Res proto.InternalMessageInfo

func (m *Res) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*FileInfo)(nil), "FileInfo")
	proto.RegisterType((*FileData)(nil), "FileData")
	proto.RegisterType((*Res)(nil), "Res")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FileTransferServiceClient is the client API for FileTransferService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FileTransferServiceClient interface {
	GetFileInfo(ctx context.Context, in *FileInfo, opts ...grpc.CallOption) (*Res, error)
	TransferFile(ctx context.Context, opts ...grpc.CallOption) (FileTransferService_TransferFileClient, error)
}

type fileTransferServiceClient struct {
	cc *grpc.ClientConn
}

func NewFileTransferServiceClient(cc *grpc.ClientConn) FileTransferServiceClient {
	return &fileTransferServiceClient{cc}
}

func (c *fileTransferServiceClient) GetFileInfo(ctx context.Context, in *FileInfo, opts ...grpc.CallOption) (*Res, error) {
	out := new(Res)
	err := c.cc.Invoke(ctx, "/FileTransferService/getFileInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileTransferServiceClient) TransferFile(ctx context.Context, opts ...grpc.CallOption) (FileTransferService_TransferFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_FileTransferService_serviceDesc.Streams[0], "/FileTransferService/transferFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &fileTransferServiceTransferFileClient{stream}
	return x, nil
}

type FileTransferService_TransferFileClient interface {
	Send(*FileData) error
	CloseAndRecv() (*Res, error)
	grpc.ClientStream
}

type fileTransferServiceTransferFileClient struct {
	grpc.ClientStream
}

func (x *fileTransferServiceTransferFileClient) Send(m *FileData) error {
	return x.ClientStream.SendMsg(m)
}

func (x *fileTransferServiceTransferFileClient) CloseAndRecv() (*Res, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Res)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FileTransferServiceServer is the server API for FileTransferService service.
type FileTransferServiceServer interface {
	GetFileInfo(context.Context, *FileInfo) (*Res, error)
	TransferFile(FileTransferService_TransferFileServer) error
}

func RegisterFileTransferServiceServer(s *grpc.Server, srv FileTransferServiceServer) {
	s.RegisterService(&_FileTransferService_serviceDesc, srv)
}

func _FileTransferService_GetFileInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileTransferServiceServer).GetFileInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FileTransferService/GetFileInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileTransferServiceServer).GetFileInfo(ctx, req.(*FileInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileTransferService_TransferFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FileTransferServiceServer).TransferFile(&fileTransferServiceTransferFileServer{stream})
}

type FileTransferService_TransferFileServer interface {
	SendAndClose(*Res) error
	Recv() (*FileData, error)
	grpc.ServerStream
}

type fileTransferServiceTransferFileServer struct {
	grpc.ServerStream
}

func (x *fileTransferServiceTransferFileServer) SendAndClose(m *Res) error {
	return x.ServerStream.SendMsg(m)
}

func (x *fileTransferServiceTransferFileServer) Recv() (*FileData, error) {
	m := new(FileData)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _FileTransferService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "FileTransferService",
	HandlerType: (*FileTransferServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getFileInfo",
			Handler:    _FileTransferService_GetFileInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "transferFile",
			Handler:       _FileTransferService_TransferFile_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_service_38b27f0a3a5b3f28) }

var fileDescriptor_service_38b27f0a3a5b3f28 = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8f, 0x31, 0x8f, 0xc2, 0x20,
	0x1c, 0xc5, 0x8f, 0x6b, 0x73, 0x77, 0xfd, 0x5f, 0xbb, 0x70, 0x0b, 0xb9, 0x41, 0x09, 0x2e, 0x4c,
	0x1d, 0xf4, 0x2b, 0x98, 0x26, 0xae, 0xe8, 0xe8, 0x82, 0xf6, 0xdf, 0xa6, 0x89, 0x2d, 0x06, 0x88,
	0x83, 0x9f, 0xde, 0x40, 0x8b, 0xdb, 0x8f, 0xf7, 0x1e, 0x8f, 0x07, 0x54, 0x0e, 0xed, 0x63, 0xb8,
	0x62, 0x7d, 0xb7, 0xc6, 0x1b, 0xd1, 0xc0, 0x4f, 0x33, 0xdc, 0xf0, 0x30, 0x75, 0x86, 0x52, 0xc8,
	0x27, 0x3d, 0x22, 0x23, 0x9c, 0xc8, 0x42, 0x45, 0x0e, 0x9a, 0x1b, 0x9e, 0xc8, 0x3e, 0x39, 0x91,
	0x99, 0x8a, 0x1c, 0xb4, 0xd1, 0xb4, 0xc8, 0x32, 0x4e, 0x64, 0xa5, 0x22, 0x8b, 0xd5, 0xdc, 0xb3,
	0xd7, 0x5e, 0x07, 0xbf, 0xd5, 0x5e, 0xc7, 0x9e, 0x52, 0x45, 0x16, 0x6b, 0xc8, 0x14, 0x3a, 0xca,
	0xe0, 0x7b, 0x44, 0xe7, 0x74, 0x9f, 0x5e, 0x49, 0xc7, 0xed, 0x19, 0xfe, 0x42, 0xc1, 0xc9, 0xea,
	0xc9, 0x75, 0x68, 0x8f, 0xf3, 0x4a, 0xca, 0xe1, 0xb7, 0x47, 0xff, 0x9e, 0x58, 0xd4, 0x09, 0xff,
	0xf3, 0x5a, 0xa1, 0x13, 0x1f, 0x74, 0x03, 0xa5, 0x5f, 0x2e, 0x05, 0x6f, 0x89, 0x84, 0x21, 0x29,
	0x22, 0xc9, 0xe5, 0x2b, 0xfe, 0x76, 0xf7, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xa7, 0x23, 0x9e, 0xb7,
	0xfe, 0x00, 0x00, 0x00,
}
